// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/log-prayer.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
  }
  return null;
}
var PRAYERS = ["fajr", "dhuhr", "asr", "maghrib", "isha"];
var PRAYER_STATUSES = ["jamaah", "ontime", "late", "missed", "none"];

// src/lib/mcp/tools/log-prayer.ts
var log_prayer_default = defineTool({
  name: "log_prayer",
  title: "Log a prayer",
  description: "Record the status of one of the five daily fard prayers for a given date. Status 'jamaah' = prayed in congregation, 'ontime' = prayed on time alone, 'late' = prayed after the window, 'missed' = did not pray, 'none' = clear the entry.",
  inputSchema: {
    date: z.string().describe("ISO date YYYY-MM-DD. Defaults to today if omitted.").optional(),
    prayer: z.enum(PRAYERS),
    status: z.enum(PRAYER_STATUSES)
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, prayer, status }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const supabase = supabaseForUser(ctx);
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const user_id = ctx.getUserId();
    if (status === "none") {
      const { error: error2 } = await supabase.from("prayer_logs").delete().match({ user_id, date: d, prayer });
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return { content: [{ type: "text", text: `Cleared ${prayer} on ${d}.` }] };
    }
    const { data, error } = await supabase.from("prayer_logs").upsert(
      { user_id, date: d, prayer, status, updated_at: (/* @__PURE__ */ new Date()).toISOString() },
      { onConflict: "user_id,date,prayer" }
    ).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${prayer} = ${status} on ${d}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/get-prayer-day.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_prayer_day_default = defineTool2({
  name: "get_prayer_day",
  title: "Get prayers for a day",
  description: "Return the status of all five fard prayers for a given date (defaults to today).",
  inputSchema: {
    date: z2.string().describe("ISO date YYYY-MM-DD. Defaults to today.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("prayer_logs").select("prayer,status,logged_at").eq("user_id", ctx.getUserId()).eq("date", d);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byPrayer = Object.fromEntries(PRAYERS.map((p) => [p, "none"]));
    for (const row of data ?? []) byPrayer[row.prayer] = row.status;
    const summary = PRAYERS.map((p) => `${p}: ${byPrayer[p]}`).join(", ");
    return {
      content: [{ type: "text", text: `${d} \u2014 ${summary}` }],
      structuredContent: { date: d, prayers: byPrayer }
    };
  }
});

// src/lib/mcp/tools/get-qadha-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_qadha_summary_default = defineTool3({
  name: "get_qadha_summary",
  title: "Get qadha (missed prayer) backlog",
  description: "Return the remaining count of missed prayers per prayer type, and the total.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const { data, error } = await supabaseForUser(ctx).from("qadha_counts").select("prayer,remaining").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byPrayer = {};
    let total = 0;
    for (const row of data ?? []) {
      byPrayer[row.prayer] = row.remaining;
      total += row.remaining;
    }
    const lines = Object.entries(byPrayer).map(([p, n]) => `${p}: ${n}`).join(", ");
    return {
      content: [{ type: "text", text: `Qadha remaining \u2014 ${lines || "none logged"} (total ${total}).` }],
      structuredContent: { total, remaining: byPrayer }
    };
  }
});

// src/lib/mcp/tools/adjust-qadha.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var QADHA_PRAYERS = ["fajr", "dhuhr", "asr", "maghrib", "isha", "witr"];
var adjust_qadha_default = defineTool4({
  name: "adjust_qadha",
  title: "Adjust qadha count",
  description: "Increment or decrement the remaining missed-prayer count for one prayer. Positive delta adds to the backlog, negative delta subtracts (e.g. after making up a prayer).",
  inputSchema: {
    prayer: z3.enum(QADHA_PRAYERS),
    delta: z3.number().int().describe("Signed integer, e.g. -1 to make up one prayer, +5 to add five."),
    reason: z3.string().max(200).optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ prayer, delta, reason }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    const { data: current } = await supabase.from("qadha_counts").select("remaining").eq("user_id", user_id).eq("prayer", prayer).maybeSingle();
    const nextValue = Math.max(0, (current?.remaining ?? 0) + delta);
    const { error: upErr } = await supabase.from("qadha_counts").upsert(
      { user_id, prayer, remaining: nextValue, updated_at: (/* @__PURE__ */ new Date()).toISOString() },
      { onConflict: "user_id,prayer" }
    );
    if (upErr) return { content: [{ type: "text", text: upErr.message }], isError: true };
    await supabase.from("qadha_events").insert({ user_id, prayer, delta, reason: reason ?? null });
    return {
      content: [{ type: "text", text: `${prayer} qadha: ${current?.remaining ?? 0} \u2192 ${nextValue}.` }],
      structuredContent: { prayer, remaining: nextValue, delta }
    };
  }
});

// src/lib/mcp/tools/list-habits.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_habits_default = defineTool5({
  name: "list_habits",
  title: "List habits",
  description: "List the user's active habits with today's completion count and daily target.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data: habits, error } = await supabase.from("habits").select("id,name,target_per_day,points").eq("user_id", user_id).eq("archived", false);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (habits ?? []).map((h) => h.id);
    let logs = [];
    if (ids.length) {
      const { data } = await supabase.from("habit_logs").select("habit_id,count").eq("user_id", user_id).eq("date", today).in("habit_id", ids);
      logs = data ?? [];
    }
    const doneById = new Map(logs.map((l) => [l.habit_id, l.count]));
    const rows = (habits ?? []).map((h) => ({
      id: h.id,
      name: h.name,
      target: h.target_per_day,
      done_today: doneById.get(h.id) ?? 0,
      points: h.points
    }));
    const lines = rows.length ? rows.map((r) => `${r.name}: ${r.done_today}/${r.target}`).join("\n") : "No habits yet.";
    return { content: [{ type: "text", text: lines }], structuredContent: { habits: rows } };
  }
});

// src/lib/mcp/tools/log-habit.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var log_habit_default = defineTool6({
  name: "log_habit",
  title: "Log habit completion",
  description: "Set today's completion count for a habit (by id or exact name). Pass count=0 to clear today's entry.",
  inputSchema: {
    habit_id: z4.string().uuid().optional(),
    habit_name: z4.string().optional(),
    count: z4.number().int().min(0),
    date: z4.string().describe("ISO date YYYY-MM-DD. Defaults to today.").optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ habit_id, habit_name, count, date }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    if (!habit_id && !habit_name) {
      return { content: [{ type: "text", text: "Provide habit_id or habit_name." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let resolvedId = habit_id;
    if (!resolvedId) {
      const { data } = await supabase.from("habits").select("id").eq("user_id", user_id).ilike("name", habit_name).maybeSingle();
      if (!data) {
        return { content: [{ type: "text", text: `No habit named "${habit_name}".` }], isError: true };
      }
      resolvedId = data.id;
    }
    const { error } = await supabase.from("habit_logs").upsert(
      { user_id, habit_id: resolvedId, date: d, count, updated_at: (/* @__PURE__ */ new Date()).toISOString() },
      { onConflict: "habit_id,date" }
    );
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Habit set to ${count} on ${d}.` }] };
  }
});

// src/lib/mcp/tools/get-insights-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_insights_summary_default = defineTool7({
  name: "get_insights_summary",
  title: "Get insights summary",
  description: "Return a summary of the last 7 days: prayer status counts, habits completed, and total qadha remaining.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    const since = new Date(Date.now() - 6 * 24 * 60 * 60 * 1e3).toISOString().slice(0, 10);
    const [{ data: prayers }, { data: habitLogs }, { data: qadha }] = await Promise.all([
      supabase.from("prayer_logs").select("status").eq("user_id", user_id).gte("date", since),
      supabase.from("habit_logs").select("count").eq("user_id", user_id).gte("date", since),
      supabase.from("qadha_counts").select("remaining").eq("user_id", user_id)
    ]);
    const byStatus = {};
    for (const p of prayers ?? []) byStatus[p.status] = (byStatus[p.status] ?? 0) + 1;
    const habitCompletions = (habitLogs ?? []).reduce((s, l) => s + (l.count ?? 0), 0);
    const qadhaTotal = (qadha ?? []).reduce((s, r) => s + (r.remaining ?? 0), 0);
    return {
      content: [
        {
          type: "text",
          text: `Last 7 days \u2014 prayers: ${JSON.stringify(byStatus)}, habit completions: ${habitCompletions}, qadha remaining: ${qadhaTotal}.`
        }
      ],
      structuredContent: {
        window_days: 7,
        prayers_by_status: byStatus,
        habit_completions: habitCompletions,
        qadha_remaining_total: qadhaTotal
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rflirpyjrklzyuwxsaxe";
var mcp_default = defineMcp({
  name: "ibadah-mcp",
  title: "Ibadah Tracker",
  version: "0.1.0",
  instructions: "Tools for the user's Ibadah tracker: log and read fard prayers, manage the qadha (missed prayer) backlog, and record habit completions. All actions run as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    log_prayer_default,
    get_prayer_day_default,
    get_qadha_summary_default,
    adjust_qadha_default,
    list_habits_default,
    log_habit_default,
    get_insights_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
